### ISSUE TITLE
cleanup untracked files

### ISSUE THREAD

**Issue by joprice** [plippe/sbt-awss3pages#21] opened 2019-02-14 21:38 UTC
Is there an option to delete old files that are present in the bucket, but have been removed from the repo? Like `s3 sync --delete`

**Comment by plippe** [comment] 2019-02-14 22:04
Hey @joprice , not 100% sure I understand.

The short version, this lib never deletes, and overwrites what is present in the `s3://bucket/prefix/...`. This avoids deleting the wrong file.

I could add a way to delete all files in `s3://bucket/prefix/...` before the put, but it could be an expensive command. The API doesn't seem to have a delete with prefix, and would require a scan, and a few build deletes.

I can look at it over the weekend if you think it is worth it.

**Comment by joprice** [comment] 2019-02-15 12:30
I was referring to functionality provided by the aws cli. You can see the docs for the `--delete` flag here https://docs.aws.amazon.com/cli/latest/reference/s3/sync.html. It's very common to use when syncing data to s3. I'm not sure about the implementation, but I think only the delta gets removed. It probably does a list of the prefix, and then diffs the entries with the new set to see what to delete. It also tries to avoid re-pushing files that haven't changed: `A s3 object will require copying if the sizes of the two s3 objects differ, the last modified time of the source is newer than the last modified time of the destination, or the s3 object does not exist under the specified bucket and prefix destination.`

**Comment by plippe** [comment] 2019-02-15 13:29
The [official library](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/index.html) doesn't seem to support sync, but would allow what you described. 

Will look at replacing the current upload by a custom made "sync".

**Comment by plippe** [comment] 2019-02-16 14:46
The update has been released under the [0.0.2](https://bintray.com/plippe/sbt/sbt-awss3pages/0.0.2) version. 

I hope that solves your issue.

**Comment by joprice** [comment] 2019-02-16 22:07
Nice! I'll try it out and let you know. I took a cursory look at the changes and it looks like you overwrite whenever size is different, but what if they have identical size but different content? The aws docs mentioned using modified date. It looks like that is available here https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/model/S3ObjectSummary.html#getLastModified--

**Comment by joprice** [comment] 2019-02-16 22:52
I tested out removing a file and syncing and everything seems to work as expected. However, it does have the issue I mentioned with identical length files. I tested this by changing the word "url" to "uri" and no change was pushed. Changing it to "ur" pushed the file however.

**Comment by plippe** [comment] 2019-02-17 10:02
The issue is that the documentation isn't version controlled, it is
generated. This makes comparing dates unreliable.

I only used length, because I doubt their will be many documentation
changes without any size differences.

To be 100% sure, I can compare file hashes. It would slow down the process,
but avoid the issue you are seeing.

**Comment by joprice** [comment] 2019-02-18 01:28
Ah, right. I only tested it on a checked-in folder that I added as a mapping. The remaining files are generated. But I think all of them would suffer from this issue. I would be fine with the cost of hashing, or even overwriting all files that should be there. Both situations leave me in a correct state, and solve the original issue of deleting missing files.

**Comment by plippe** [comment] 2019-02-20 12:21
@joprice, does the new version fix the issue ?

**Comment by joprice** [comment] 2019-02-20 13:45
I think I need your latest unreleased commits. Should I `publishLocal`?

**Comment by plippe** [comment] 2019-02-20 14:51
The repo is published after each merge: [0.0.2-1-g934d971](https://bintray.com/plippe/sbt/sbt-awss3pages/0.0.2-1-g934d971). 

The version number is generated with [sbt-git](https://github.com/sbt/sbt-git). It isn't "sexy", but it works.

**Comment by joprice** [comment] 2019-02-22 13:12
Just tried it. Works great! Thanks for the quick response.

**Comment by plippe** [comment] 2019-02-22 16:23
No worries, we got there in the end :D
Do you mind if I close the issue ?

**Closed** 2019-02-22 16:31 UTC
